/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.form;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Gogic
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblKomercijalista = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDestinacija = new javax.swing.JTable();
        btnOpenAranzman = new javax.swing.JButton();
        btnUpdateDestinacija = new javax.swing.JButton();
        btnInsertDestinacija = new javax.swing.JButton();
        txtSearchDestinacija = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnResetTable = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("[Client] - agency v1.0");

        lblKomercijalista.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblKomercijalista.setText("Komercijalista: ");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Destinacije"));

        tblDestinacija.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDestinacija.setRowHeight(22);
        jScrollPane1.setViewportView(tblDestinacija);

        btnOpenAranzman.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnOpenAranzman.setText("Otvori aranžmane");

        btnUpdateDestinacija.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnUpdateDestinacija.setText("Izmeni destinaciju");

        btnInsertDestinacija.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnInsertDestinacija.setText("Dodaj destinaciju");

        btnSearch.setText("Pretraži");

        btnResetTable.setText("Resetuj tabelu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtSearchDestinacija)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(186, 186, 186))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 545, Short.MAX_VALUE)
                                .addComponent(btnResetTable, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOpenAranzman, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateDestinacija, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertDestinacija, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnInsertDestinacija, btnOpenAranzman, btnUpdateDestinacija});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnOpenAranzman)
                        .addGap(18, 18, 18)
                        .addComponent(btnInsertDestinacija)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateDestinacija))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchDestinacija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(btnResetTable))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnInsertDestinacija, btnOpenAranzman, btnUpdateDestinacija});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblKomercijalista, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblKomercijalista, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prepareForm() {
        setLocationRelativeTo(null);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsertDestinacija;
    private javax.swing.JButton btnOpenAranzman;
    private javax.swing.JButton btnResetTable;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdateDestinacija;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblKomercijalista;
    private javax.swing.JTable tblDestinacija;
    private javax.swing.JTextField txtSearchDestinacija;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnInsertDestinacija() {
        return btnInsertDestinacija;
    }

    public JButton getBtnOpenAranzman() {
        return btnOpenAranzman;
    }

    public JButton getBtnSearch() {
        return btnSearch;
    }

    public JButton getBtnUpdateDestinacija() {
        return btnUpdateDestinacija;
    }

    public JLabel getLblKomercijalista() {
        return lblKomercijalista;
    }

    public JTable getTblDestinacija() {
        return tblDestinacija;
    }

    public JTextField getTxtSearchDestinacija() {
        return txtSearchDestinacija;
    }

    public void addBtnInsertDestinacijaActionListener(ActionListener actionListener) {
        btnInsertDestinacija.addActionListener(actionListener);
    }

    public void addBtnOpenAranzmanActionListener(ActionListener actionListener) {
        btnOpenAranzman.addActionListener(actionListener);
    }

    public void addBtnSearchActionListener(ActionListener actionListener) {
        btnSearch.addActionListener(actionListener);
    }

    public void addBtnUpdateDestinacijaActionListener(ActionListener actionListener) {
        btnUpdateDestinacija.addActionListener(actionListener);
    }

    public void addBtnResetTableActionListener(ActionListener actionListener) {
        btnResetTable.addActionListener(actionListener);
    }

    public JButton getBtnResetTable() {
        return btnResetTable;
    }



    public void setColumnWidth() {
        
        DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();
        cellRenderer.setHorizontalAlignment(JLabel.CENTER);
        tblDestinacija.getColumnModel().getColumn(2).setPreferredWidth(150);
        tblDestinacija.getColumnModel().getColumn(2).setMaxWidth(150);
        tblDestinacija.getColumnModel().getColumn(2).setCellRenderer(cellRenderer);
        tblDestinacija.getColumnModel().getColumn(3).setPreferredWidth(150);
        tblDestinacija.getColumnModel().getColumn(3).setMaxWidth(150);
        tblDestinacija.getColumnModel().getColumn(3).setCellRenderer(cellRenderer);
        tblDestinacija.getColumnModel().getColumn(0).setPreferredWidth(250);
        tblDestinacija.getColumnModel().getColumn(0).setMaxWidth(250);
        tblDestinacija.getColumnModel().getColumn(1).setMinWidth(300);

    }

}
