/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.form;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Gogic
 */
public class FrmUgovor extends javax.swing.JDialog {

    /**
     * Creates new form FrmUgovor
     */
    public FrmUgovor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblBrojKlijenata = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblBrojKreveta = new javax.swing.JLabel();
        lblSmestaj = new javax.swing.JLabel();
        lblDestinacija = new javax.swing.JLabel();
        lblKomercijalista = new javax.swing.JLabel();
        lblBrojUgovora = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblUkupnaCena = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblDatum = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavkeUgovora = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtImeIPrezimeKlijenta = new javax.swing.JTextField();
        txtJMBG = new javax.swing.JTextField();
        txtCena = new javax.swing.JTextField();
        btnUnesiKlijenta = new javax.swing.JButton();
        btnObrisiKlijenta = new javax.swing.JButton();
        btnObradi = new javax.swing.JButton();
        btnOdustani = new javax.swing.JButton();
        btnStorniraj = new javax.swing.JButton();
        btnPretraziUBazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ugovor");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ugovor"));

        jLabel4.setText("Komercijalista:");

        jLabel1.setText("Destinacija:");

        jLabel2.setText("Smestaj:");

        jLabel3.setText("Broj klijenata:");

        jLabel5.setText("Broj ugovora:");

        lblBrojKlijenata.setText("jLabel6");

        jLabel6.setText("Broj kreveta:");

        lblBrojKreveta.setText("jLabel6");

        lblSmestaj.setText("jLabel6");

        lblDestinacija.setText("jLabel6");

        lblKomercijalista.setText("jLabel6");

        lblBrojUgovora.setText("jLabel6");

        jLabel10.setText("Ukupna cena:");

        lblUkupnaCena.setText("jLabel11");

        jLabel11.setText("Datum ugovora:");

        lblDatum.setText("jLabel12");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblSmestaj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(lblDestinacija, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBrojKreveta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblBrojKlijenata, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lblBrojUgovora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUkupnaCena, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(96, 96, 96))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(lblKomercijalista, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(lblDestinacija)
                    .addComponent(lblKomercijalista))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(lblSmestaj)
                    .addComponent(lblBrojUgovora)
                    .addComponent(jLabel11)
                    .addComponent(lblDatum))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblBrojKlijenata)
                    .addComponent(jLabel6)
                    .addComponent(lblBrojKreveta)
                    .addComponent(jLabel10)
                    .addComponent(lblUkupnaCena))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblStavkeUgovora.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblStavkeUgovora.setRowHeight(22);
        jScrollPane1.setViewportView(tblStavkeUgovora);

        jLabel7.setText("Ime i prezime klijenta:");

        jLabel8.setText("JMBG:");

        jLabel9.setText("Cena:");

        btnUnesiKlijenta.setText("Unesi klijenta");

        btnObrisiKlijenta.setText("Obrisi klijenta");

        btnObradi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnObradi.setText("Obradi ugovor");

        btnOdustani.setText("Odustani");

        btnStorniraj.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnStorniraj.setText("Storniraj ugovor");

        btnPretraziUBazi.setText("Pretrazi u bazi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUnesiKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnObrisiKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtImeIPrezimeKlijenta)
                                    .addComponent(txtCena, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnPretraziUBazi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnStorniraj, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                .addComponent(btnOdustani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnObradi, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnObradi, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtImeIPrezimeKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(txtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnPretraziUBazi, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btnStorniraj, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUnesiKlijenta)
                    .addComponent(btnObrisiKlijenta)
                    .addComponent(btnOdustani))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnObradi() {
        return btnObradi;
    }

    public JButton getBtnObrisiKlijenta() {
        return btnObrisiKlijenta;
    }

    public JButton getBtnOdustani() {
        return btnOdustani;
    }

    public JButton getBtnStorniraj() {
        return btnStorniraj;
    }

    public JButton getBtnUnesiKlijenta() {
        return btnUnesiKlijenta;
    }

    public JLabel getLblBrojKlijenata() {
        return lblBrojKlijenata;
    }

    public JLabel getLblBrojKreveta() {
        return lblBrojKreveta;
    }

    public JLabel getLblBrojUgovora() {
        return lblBrojUgovora;
    }

    public JLabel getLblDestinacija() {
        return lblDestinacija;
    }

    public JLabel getLblKomercijalista() {
        return lblKomercijalista;
    }

    public JLabel getLblSmestaj() {
        return lblSmestaj;
    }

    public JTable getTblStavkeUgovora() {
        return tblStavkeUgovora;
    }

    public JTextField getTxtCena() {
        return txtCena;
    }

    public JLabel getLblUkupnaCena() {
        return lblUkupnaCena;
    }

    public JTextField getTxtImeIPrezimeKlijenta() {
        return txtImeIPrezimeKlijenta;
    }

    public JTextField getTxtJMBG() {
        return txtJMBG;
    }

    public JButton getBtnPretraziUBazi() {
        return btnPretraziUBazi;
    }

    public JLabel getLblDatum() {
        return lblDatum;
    }

    public void addBtnObradiUgovorActionListener(ActionListener actionListener) {
        btnObradi.addActionListener(actionListener);
    }

    public void addBtnObrisiKlijentaActionListener(ActionListener actionListener) {
        btnObrisiKlijenta.addActionListener(actionListener);
    }

    public void addBtnOdustaniActionListener(ActionListener actionListener) {
        btnOdustani.addActionListener(actionListener);
    }

    public void addBtnStornirajUgovorActionListener(ActionListener actionListener) {
        btnStorniraj.addActionListener(actionListener);
    }

    public void addBtnUnesiKlijentaActionListener(ActionListener actionListener) {
        btnUnesiKlijenta.addActionListener(actionListener);
    }
    
     public void addBtnPretraziUBaziActionListener(ActionListener actionListener) {
        btnPretraziUBazi.addActionListener(actionListener);
    }

    public void setColumnWidth() {

        DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();
        cellRenderer.setHorizontalAlignment(JLabel.CENTER);

        tblStavkeUgovora.getColumnModel().getColumn(2).setCellRenderer(cellRenderer);

        tblStavkeUgovora.getColumnModel().getColumn(3).setPreferredWidth(150);
        tblStavkeUgovora.getColumnModel().getColumn(3).setMaxWidth(150);
        tblStavkeUgovora.getColumnModel().getColumn(3).setCellRenderer(cellRenderer);

        tblStavkeUgovora.getColumnModel().getColumn(0).setPreferredWidth(150);
        tblStavkeUgovora.getColumnModel().getColumn(0).setMaxWidth(150);
        tblStavkeUgovora.getColumnModel().getColumn(0).setCellRenderer(cellRenderer);

        tblStavkeUgovora.getColumnModel().getColumn(1).setPreferredWidth(300);
        tblStavkeUgovora.getColumnModel().getColumn(1).setMinWidth(300);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObradi;
    private javax.swing.JButton btnObrisiKlijenta;
    private javax.swing.JButton btnOdustani;
    private javax.swing.JButton btnPretraziUBazi;
    private javax.swing.JButton btnStorniraj;
    private javax.swing.JButton btnUnesiKlijenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBrojKlijenata;
    private javax.swing.JLabel lblBrojKreveta;
    private javax.swing.JLabel lblBrojUgovora;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblDestinacija;
    private javax.swing.JLabel lblKomercijalista;
    private javax.swing.JLabel lblSmestaj;
    private javax.swing.JLabel lblUkupnaCena;
    private javax.swing.JTable tblStavkeUgovora;
    private javax.swing.JTextField txtCena;
    private javax.swing.JTextField txtImeIPrezimeKlijenta;
    private javax.swing.JTextField txtJMBG;
    // End of variables declaration//GEN-END:variables
}
